allowBuilds:
  "@tailwindcss/oxide": true
  esbuild: true

overrides:
  chokidar: ^5.0.0
  semver: ^7.0.0

blockExoticSubdeps: true
minimumReleaseAge: 1440
trustPolicy: no-downgrade
engineStrict: true
preferFrozenLockfile: true
